### ISSUE TITLE
example

### ISSUE THREAD

**Issue by ehartford** [fblissjr/mlx-funbox#1]
can you please show some examples in the readme?

**Comment by fblissjr** [comment]
yep, working on it, literally just whipped it together, and finding the cohere prompt template isn't doing what i want.

cat fff.py | python fff.py "Summarize" --temp 0.0 --model ./mlx-community_c4ai-command-r-plus-4bit

**Comment by fblissjr** [comment]
i hit a deadend for the night - kid time begins. something with piping in the values and there not being a default chat template in the tokenizer.

**Comment by fblissjr** [comment]
got it working. add_generation_prompt=True for when the chat template is missing in the tokenizer config is what fixed it.

**Comment by fblissjr** [comment]
uploading new commit
